version: "3.9"
services:
  postgres15:
    container_name: postgres15
    image: postgres:15-alpine
    ports:
      - "5532:5432"
    environment:
      POSTGRES_PASSWORD: 181277
      POSTGRES_DB: aex_db
    volumes:
      - data-postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - aex
  mysql8:
    container_name: mysql8
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 181277
      MYSQL_DATABASE: aex_webapp_1
    volumes:
      - data-mysql:/var/lib/mysql
    restart: always
    networks:
      - aex
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:5
    ports:
      - "7080:80"
    restart: always
    environment:
      - PMA_ARBITRARY=1
      - UPLOAD_LIMIT=128M
      - MAX_EXECUTION_TIME=128M
    networks:
      - aex
    depends_on:
      - mysql8
  aex-system:
    container_name: aex-system
    image: estarlinlopez/aex
#    build:
#      context: ./
#      dockerfile: ./Dockerfile
    ports:
      - "8000:7000"
    environment:
      DB_HOST: postgres15
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: 181277
      DB_DATABASE: aex_db
    networks:
      - aex
    depends_on:
      - postgres15
    restart: always

volumes:
  data-postgres:
    name: data-postgres
  data-mysql:
    name: data-mysql

networks:
  aex:
    name: aex