version: "3.9"
services:
  postgres15:
    container_name: postgres15
    image: postgres:15-alpine
    ports:
      - "5532:5432"
    environment:
      POSTGRES_PASSWORD: 181277
      POSTGRES_DB: aex_db
    volumes:
      - data-postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - aex

  aex-system:
    container_name: aex-system
    image: estarlinlopez/aex
#    build:
#      context: ./
#      dockerfile: ./Dockerfile
    ports:
      - "8000:7000"
    environment:
      DB_HOST: postgres15
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: 181277
      DB_DATABASE: aex_db
    networks:
      - aex
    depends_on:
      - postgres15
    restart: always

volumes:
  data-postgres:
    name: data-postgres

networks:
  aex:
    name: aex