spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: programadorvillao@gmail.com
    password: hnroyzinjtivzfhr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres15}:${DB_PORT:5432}/${DB_DATABASE:aex_db}
    #url: jdbc:postgresql://localhost:5432/aex_db
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:181277}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      #ddl-auto: create-drop
      #ddl-auto: create-only
     ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  http:
    multipart:
      enabled: true

server:
  port: ${PORT:7000}

application:
  name: mscio-bank-transfer
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
